apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  namespace: "flux-system"
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc