apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.pod.name }}"
  namespace: "{{ .Values.pod.namespace }}"
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc